#bruh, dat's the only one tho
tweaksplusplus-patcher:
	$(CC) -o $@ main.c $(STLDFLAGS)
clean:
	rm tweaksplusplus-patcher
user-install:
	cp tweaksplusplus-patcher ${HOME}/.local/bin
user-uninstall:
	rm ${HOME}/.local/bin/tweaksplusplus-patcher

